In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("50_startups.csv")

In [3]:
dataset

    R&D Spend  Administartion  Mrketing Spend       State  Profit
0      165616          165754           41479    New York   19683
1      165026          165062           54009  California   17942
2      165192          165584           43133  California   15659
3      165026          165738           51609    New York   19604
4      165264          165011           46877  California   22525
5      165193          165165           43990  California   21121
6      165478          165880           50919  California   24060
7      165732          165208           40310  California   21456
8      165292          165761           54439    New York   20967
9      165480          165878           52484  California   17102
10     165072          165912           41630  California   22923
11     165726          165436           41399  California   15643
12     165079          165271           41943  California   21197
13     165292          165800           51531    New York   16004
14     165263          165378           42778  California   22290
15     165073          165349           52486  California   16551
16     165930          165718           50574    New York   17180

In [15]:

dataset = pd.get_dummies(dataset,drop_first=True)

In [24]:
dataset

,R&D Spend,Administartion,Mrketing Spend,Profit,State_California,State_New York
0,165616,165754,41479,19683,0,1
1,165026,165062,54009,17942,1,0
2,165192,165584,43133,15659,1,0
3,165026,165738,51609,19604,0,1
4,165264,165011,46877,22525,1,0
5,165193,165165,43990,21121,1,0
6,165478,165880,50919,24060,1,0
7,165732,165208,40310,21456,1,0
8,165292,165761,54439,20967,0,1
9,165480,165878,52484,17102,1,0
10,165072,165912,41630,22923,1,0
11,165726,165436,41399,15643,1,0
12,165079,165271,41943,21197,1,0
13,165292,165800,51531,16004,0,1
14,165263,165378,42778,22290,1,0
15,165073,165349,52486,16551,1,0
16,165930,165718,50574,17180,0,1

In [23]:
dataset.columns

Index(['R&D Spend', 'Administartion', 'Mrketing Spend', 'Profit',
       'State_California', 'State_New York'],
      dtype='object')

In [27]:
independent = dataset[['R&D Spend', 'Administartion', 'Mrketing Spend',
       'State_California', 'State_New York']]

In [28]:
independent

,R&D Spend,Administartion,Mrketing Spend,State_California,State_New York
0,165616,165754,41479,0,1
1,165026,165062,54009,1,0
2,165192,165584,43133,1,0
3,165026,165738,51609,0,1
4,165264,165011,46877,1,0
5,165193,165165,43990,1,0
6,165478,165880,50919,1,0
7,165732,165208,40310,1,0
8,165292,165761,54439,0,1
9,165480,165878,52484,1,0
10,165072,165912,41630,1,0
11,165726,165436,41399,1,0
12,165079,165271,41943,1,0
13,165292,165800,51531,0,1
14,165263,165378,42778,1,0
15,165073,165349,52486,1,0
16,165930,165718,50574,0,1

In [31]:
dependent=dataset[['Profit']]

In [32]:
dependent

    Profit
0    19683
1    17942
2    15659
3    19604
4    22525
5    21121
6    24060
7    21456
8    20967
9    17102
10   22923
11   15643
12   21197
13   16004
14   22290
15   16551
16   17180

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [35]:
weight=regressor.coef_
weight

array([[-4.56053139e+00, -2.43714561e+00, -3.96735230e-01,
        -1.41247454e+03,  1.41247454e+03]])

In [36]:
bias=regressor.intercept_
bias

array([1195210.23769042])

In [37]:
y_pred=regressor.predict(X_test)

In [38]:
from sklearn.metrics import r2_score
r2_score=r2_score(Y_test,y_pred)
r2_score

-1.4462203541353085

In [39]:
r2_score

-1.4462203541353085

In [40]:
import pickle 
filename="finalized_model_linear.sav"

In [41]:
pickle.dump(regressor,open(filename,'wb'))

In [43]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[1234,343,5432,1,0]])

C:\Users\acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [44]:
result

array([[1185179.06070708]])